[package]
name = "eva-npu-c-api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
libc = "0.2"

[dependencies.intel-npu]
path = "../drive"

[build-dependencies]
cbindgen = "0.27"
